ALTER TYPE "AiTaskComplexity" ADD VALUE 'NOT_ANALYZED' BEFORE 'LOW';
ALTER TYPE "AiTaskRisk" ADD VALUE 'NOT_ANALYZED' BEFORE 'LOW';
ALTER TYPE "AiTaskAmbiguity" ADD VALUE 'NOT_ANALYZED' BEFORE 'LOW';
ALTER TYPE "AiTaskVerificationNeed" ADD VALUE 'NOT_ANALYZED' BEFORE 'LOW';
ALTER TYPE "AiTaskExpectedEffort" ADD VALUE 'NOT_ANALYZED' BEFORE 'SMALL';
ALTER TYPE "AiTaskRoutingReason" ADD VALUE 'EXPLICIT_MODE' BEFORE 'CRITICAL_RISK';
ALTER TYPE "AiTaskAnalysisSignal" ADD VALUE 'EXPLICIT_MODE' BEFORE 'SHORT_REQUEST';
