services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in .env}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - skyos-postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: pgvector/pgvector:0.8.1-pg17
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:?Set POSTGRES_TEST_DB in .env}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:?Set POSTGRES_TEST_PASSWORD in .env}
      POSTGRES_USER: ${POSTGRES_TEST_USER:?Set POSTGRES_TEST_USER in .env}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - skyos-postgres-test-data:/var/lib/postgresql/data

volumes:
  skyos-postgres-data:
  skyos-postgres-test-data:
